//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ArticleInfo
    {
        public int ID { get; set; }
        public int DicID { get; set; }
        public int SerialNum { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string IsTopArticle { get; set; }
    }
}
